name = "WildlandFire"
uuid = "a1b2c3d4-e5f6-7890-abcd-ef1234567890"
version = "0.1.0"
authors = ["EarthSciML authors and contributors"]

[deps]
DynamicQuantities = "06fc5a27-2a28-4c7c-a15d-362465fb6821"
ModelingToolkit = "961ee093-0014-501f-94e3-6117800e7a78"
OrdinaryDiffEqDefault = "50262376-6c5a-4cf5-baba-aaf4f84d72d7"

[compat]
DynamicQuantities = "1"
ModelingToolkit = "11"
OrdinaryDiffEqDefault = "1"
julia = "1.10"

[extras]
Plots = "91a5bcdd-55d7-5caf-9e0b-520d859cae80"
SciMLBase = "0bca4576-84f4-4d90-8ffe-ffa030f20462"
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"
TestItemRunner = "f8b46487-2199-4994-9208-9a1283c18c0a"

[targets]
test = ["Test", "Plots", "SciMLBase", "TestItemRunner"]
