name = "WildlandFire"
uuid = "a1b2c3d4-e5f6-7890-abcd-ef1234567890"
authors = ["EarthSciML authors and contributors"]
version = "0.1.0"

[deps]
ModelingToolkit = "961ee093-0014-501f-94e3-6117800e7a78"
OrdinaryDiffEqDefault = "50262376-6c5a-4cf5-baba-aaf4f84d72d7"

[compat]
julia = "1.10"
ModelingToolkit = "11"
OrdinaryDiffEqDefault = "1"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"
Plots = "91a5bcdd-55d7-5caf-9e0b-520d859cae80"
SciMLBase = "0bca4576-84f4-4d90-8ffe-ffa030f20462"

[targets]
test = ["Test", "Plots", "SciMLBase"]
